@startuml

left to right direction

actor User as "使用者"
actor Doctor as "醫師"
actor Administrator as "管理者"

rectangle "線上掛號系統" {
    usecase "病患線上掛號登記作業" as UC1
    usecase "查看院內所有醫師的履歷" as UC2
}

User --> UC1: 使用系統進行掛號
User --> UC2: 查看醫師履歷
Doctor --> UC1: 查看病患線上掛號登記
Administrator --> UC1: 管理系統
Administrator --> UC2: 管理系統

@enduml
